//! Curated model registry for the current platform.
//!
//! Provides platform-optimal model entries generated at build time from
//! TOML files in `registry/`. Includes memory threshold checking via a
//! `LazyLock` that captures total system RAM once on first access.

// Generated by build.rs: ModelEntry, MODELS, PlatformDefaults, DEFAULTS.
include!(concat!(env!("OUT_DIR"), "/registry.rs"));

/// Return the default text model for the current platform.
pub fn default_text() -> &'static ModelEntry {
    find_by_key(DEFAULTS.text).expect("default text model missing from registry")
}

/// Return the default vision model for the current platform, if any.
pub fn default_vision() -> Option<&'static ModelEntry> {
    DEFAULTS.vision.and_then(find_by_key)
}

/// Return the platform default quantization serde key, if any.
pub fn default_quantization() -> Option<&'static str> {
    DEFAULTS.default_quantization
}

/// Check if a HuggingFace model ID is in the registry.
pub fn is_known(model_id: &str) -> bool {
    MODELS.iter().any(|e| e.model_id == model_id)
}

/// Look up a model by HuggingFace model ID.
pub fn find(model_id: &str) -> Option<&'static ModelEntry> {
    MODELS.iter().find(|e| e.model_id == model_id)
}

/// Look up a model by registry key (e.g. "qwen3-4b").
pub fn find_by_key(key: &str) -> Option<&'static ModelEntry> {
    MODELS.iter().find(|e| e.key == key)
}

/// List all curated models for the current platform.
pub fn all() -> &'static [ModelEntry] {
    MODELS
}

/// Build a `Local` provider from a registry entry.
///
/// Uses the entry's loader and the platform default quantization.
pub fn build_local(entry: &ModelEntry) -> crate::local::Local {
    let isq = default_quantization().and_then(|q| {
        let qt: crate::config::QuantizationType = serde_json::from_str(&format!("\"{q}\"")).ok()?;
        Some(qt.to_isq())
    });
    crate::local::Local::lazy(entry.model_id, entry.loader, isq, None)
}

impl ModelEntry {
    /// Check if this model fits in the system's available RAM.
    pub fn fits(&self) -> bool {
        crate::local::system_memory() >= self.memory.bytes()
    }

    /// Return a human-readable string describing the memory requirement.
    pub fn memory_requirement(&self) -> String {
        let gb = self.memory.bytes() / (1024 * 1024 * 1024);
        format!("{gb}GB")
    }
}
