//! Curated model registry for the current platform.
//!
//! Provides platform-optimal model entries generated at build time from
//! TOML files in `registry/`. Includes memory threshold checking via a
//! `LazyLock` that captures total system RAM once on first access.

use crate::config::{ProviderConfig, QuantizationType};
use compact_str::CompactString;

// Generated by build.rs: ModelEntry, MODELS, PlatformDefaults, DEFAULTS.
include!(concat!(env!("OUT_DIR"), "/registry.rs"));

/// Return the default text model for the current platform.
pub fn default_text() -> &'static ModelEntry {
    find_by_key(DEFAULTS.text).expect("default text model missing from registry")
}

/// Return the default vision model for the current platform, if any.
pub fn default_vision() -> Option<&'static ModelEntry> {
    DEFAULTS.vision.and_then(find_by_key)
}

/// Check if a HuggingFace model ID is in the registry.
pub fn is_known(model_id: &str) -> bool {
    MODELS.iter().any(|e| e.model_id == model_id)
}

/// Look up a model by HuggingFace model ID.
pub fn find(model_id: &str) -> Option<&'static ModelEntry> {
    MODELS.iter().find(|e| e.model_id == model_id)
}

/// Look up a model by registry key (e.g. "qwen3-4b").
pub fn find_by_key(key: &str) -> Option<&'static ModelEntry> {
    MODELS.iter().find(|e| e.key == key)
}

/// List all curated models for the current platform.
pub fn all() -> &'static [ModelEntry] {
    MODELS
}

impl ModelEntry {
    /// Convert this registry entry into a `ProviderConfig`.
    pub fn to_provider_config(&self) -> ProviderConfig {
        let quantization: Option<QuantizationType> = self
            .quantization
            .map(|q| serde_json::from_str(&format!("\"{q}\"")).unwrap());
        ProviderConfig {
            model: CompactString::from(self.model_id),
            api_key: None,
            base_url: None,
            quantization,
            chat_template: None,
        }
    }

    /// Check if this model fits in the system's available RAM.
    ///
    /// Returns `true` if no memory threshold is set or if the system
    /// has enough RAM. Uses `SYSTEM_MEMORY` lazy lock.
    pub fn fits(&self) -> bool {
        match self.memory {
            Some(threshold) => crate::local::system_memory() >= threshold.bytes(),
            None => true,
        }
    }

    /// Return a human-readable string describing the memory requirement,
    /// or `None` if no threshold is set.
    pub fn memory_requirement(&self) -> Option<String> {
        self.memory.map(|t| {
            let gb = t.bytes() / (1024 * 1024 * 1024);
            format!("{gb}GB")
        })
    }
}
