//! Curated model registry for the current platform.
//!
//! Provides platform-optimal model entries generated at build time from
//! TOML files in `registry/`. Includes memory threshold checking via a
//! `LazyLock` that captures total system RAM once on first access.
//! Quantization is auto-selected based on headroom (system RAM minus
//! model memory requirement).

// Generated by build.rs: ModelEntry, MODELS, PlatformDefaults, DEFAULTS.
include!(concat!(env!("OUT_DIR"), "/registry.rs"));

const GB: u64 = 1024 * 1024 * 1024;

/// Return the default model for the current platform.
pub fn default_model() -> &'static ModelEntry {
    find_by_key(DEFAULTS.text).expect("default model missing from registry")
}

/// Check if a HuggingFace model ID is in the registry.
pub fn is_known(model_id: &str) -> bool {
    MODELS.iter().any(|e| e.model_id == model_id)
}

/// Look up a model by HuggingFace model ID.
pub fn find(model_id: &str) -> Option<&'static ModelEntry> {
    MODELS.iter().find(|e| e.model_id == model_id)
}

/// Look up a model by registry key (e.g. "qwen3-4b").
pub fn find_by_key(key: &str) -> Option<&'static ModelEntry> {
    MODELS.iter().find(|e| e.key == key)
}

/// List all curated models for the current platform.
pub fn all() -> &'static [ModelEntry] {
    MODELS
}

/// Build a `Local` provider from a registry entry.
///
/// Quantization is auto-selected based on memory headroom:
/// more headroom → less aggressive quantization → better quality.
/// GGUF models are pre-quantized and don't use ISQ.
pub fn build_local(entry: &ModelEntry) -> crate::local::Local {
    let isq = match entry.loader {
        crate::config::Loader::Gguf => None,
        _ => {
            let headroom = crate::local::system_memory().saturating_sub(entry.memory.bytes());
            recommend_isq(headroom)
        }
    };
    crate::local::Local::lazy(entry.model_id, entry.loader, isq, None)
}

/// Pick ISQ type based on available memory headroom.
///
/// Platform-specific: Metal uses AFQ variants, CUDA uses Q/K variants.
/// More headroom → higher-bit quantization → better quality.
#[cfg(feature = "metal")]
fn recommend_isq(headroom: u64) -> Option<mistralrs::IsqType> {
    Some(if headroom >= 16 * GB {
        mistralrs::IsqType::AFQ8
    } else if headroom >= 8 * GB {
        mistralrs::IsqType::AFQ6
    } else {
        mistralrs::IsqType::AFQ4
    })
}

#[cfg(feature = "cuda")]
fn recommend_isq(headroom: u64) -> Option<mistralrs::IsqType> {
    Some(if headroom >= 16 * GB {
        mistralrs::IsqType::Q8K
    } else if headroom >= 8 * GB {
        mistralrs::IsqType::Q6K
    } else {
        mistralrs::IsqType::Q4K
    })
}

#[cfg(not(any(feature = "metal", feature = "cuda")))]
fn recommend_isq(_headroom: u64) -> Option<mistralrs::IsqType> {
    // CPU platform uses GGUF models only (pre-quantized).
    None
}

impl ModelEntry {
    /// Check if this model fits in the system's available RAM.
    pub fn fits(&self) -> bool {
        crate::local::system_memory() >= self.memory.bytes()
    }

    /// Return a human-readable string describing the memory requirement.
    pub fn memory_requirement(&self) -> String {
        let gb = self.memory.bytes() / GB;
        format!("{gb}GB")
    }
}
