//! Rust code generation from parsed registry data.

use super::parse::{ModelEntry as ParsedModel, PlatformFile};
use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use std::path::Path;

/// Generate `quantization.rs` containing `MemoryThreshold`.
pub fn write_memory_threshold(out_dir: &Path) {
    let mem_variants: Vec<TokenStream> = MEMORY_THRESHOLDS
        .iter()
        .map(|(name, variant, gb)| {
            let ident = format_ident!("{}", variant);
            let doc = format!("{gb} GB minimum.");
            quote! {
                #[serde(rename = #name)]
                #[doc = #doc]
                #ident
            }
        })
        .collect();

    let mem_bytes_arms: Vec<TokenStream> = MEMORY_THRESHOLDS
        .iter()
        .map(|(_, variant, gb)| {
            let ident = format_ident!("{}", variant);
            let bytes: u64 = gb * 1024 * 1024 * 1024;
            quote! { Self::#ident => #bytes }
        })
        .collect();

    let tokens = quote! {
        #[doc = "Minimum system RAM required for a model."]
        #[doc = ""]
        #[doc = "Generated by build.rs from registry TOML files."]
        #[derive(Debug, Clone, Copy, serde::Serialize, serde::Deserialize)]
        pub enum MemoryThreshold {
            #(#mem_variants),*
        }

        impl MemoryThreshold {
            #[doc = "Return the threshold in bytes."]
            pub fn bytes(self) -> u64 {
                match self {
                    #(#mem_bytes_arms),*
                }
            }
        }
    };

    write_tokens(tokens, &out_dir.join("quantization.rs"));
}

/// Generate `registry.rs` containing `ModelEntry`, `MODELS`, `PlatformDefaults`, `DEFAULTS`.
pub fn write_registry(platform: &PlatformFile, out_dir: &Path) {
    let entries: Vec<TokenStream> = platform
        .models
        .iter()
        .map(|(key, entry)| model_entry_tokens(key, entry))
        .collect();

    let text_default = &platform.defaults.text;

    let tokens = quote! {
        #[doc = "A curated model entry from the registry."]
        #[doc = ""]
        #[doc = "Generated by build.rs from registry TOML files."]
        #[derive(Debug, Clone, Copy)]
        pub struct ModelEntry {
            #[doc = "Registry key (e.g. \"qwen3-4b\")."]
            pub key: &'static str,
            #[doc = "Human-readable name."]
            pub name: &'static str,
            #[doc = "HuggingFace model ID."]
            pub model_id: &'static str,
            #[doc = "Loader to use."]
            pub loader: crate::config::Loader,
            #[doc = "Minimum system RAM."]
            pub memory: crate::config::MemoryThreshold,
            #[doc = "GGUF filename stem for constructing quantized filenames (e.g. `Qwen3-0.6B`)."]
            pub gguf_stem: Option<&'static str>,
            #[doc = "Explicit GGUF filename override (takes priority over stem-based construction)."]
            pub gguf_file: Option<&'static str>,
        }

        #[doc = "All curated models for the current platform."]
        pub const MODELS: &[ModelEntry] = &[
            #(#entries),*
        ];

        #[doc = "Platform defaults from the registry."]
        #[derive(Debug, Clone, Copy)]
        pub struct PlatformDefaults {
            #[doc = "Default model registry key."]
            pub text: &'static str,
        }

        #[doc = "Platform defaults for the current build."]
        pub const DEFAULTS: PlatformDefaults = PlatformDefaults {
            text: #text_default,
        };
    };

    write_tokens(tokens, &out_dir.join("registry.rs"));
}

// ── Helpers ────────────────────────────────────────────────────────

const MEMORY_THRESHOLDS: &[(&str, &str, u64)] = &[
    ("4gb", "Gb4", 4),
    ("8gb", "Gb8", 8),
    ("16gb", "Gb16", 16),
    ("32gb", "Gb32", 32),
    ("64gb", "Gb64", 64),
];

fn loader_tokens(loader: &str) -> TokenStream {
    match loader {
        "text" => quote!(crate::config::Loader::Text),
        "gguf" => quote!(crate::config::Loader::Gguf),
        "vision" => quote!(crate::config::Loader::Vision),
        other => panic!("unknown loader in registry: {other}"),
    }
}

fn memory_tokens(memory: &str) -> TokenStream {
    let ident = format_ident!(
        "{}",
        MEMORY_THRESHOLDS
            .iter()
            .find(|(name, _, _)| *name == memory)
            .unwrap_or_else(|| panic!("unknown memory threshold: {memory}"))
            .1
    );
    quote!(crate::config::MemoryThreshold::#ident)
}

fn model_entry_tokens(key: &str, entry: &ParsedModel) -> TokenStream {
    let name = &entry.name;
    let model_id = &entry.model_id;
    let loader = loader_tokens(&entry.loader);
    let mem = memory_tokens(&entry.memory);
    let gguf_stem = option_str_tokens(&entry.gguf_stem);
    let gguf_file = option_str_tokens(&entry.gguf_file);

    quote! {
        ModelEntry {
            key: #key,
            name: #name,
            model_id: #model_id,
            loader: #loader,
            memory: #mem,
            gguf_stem: #gguf_stem,
            gguf_file: #gguf_file,
        }
    }
}

fn option_str_tokens(opt: &Option<String>) -> TokenStream {
    match opt {
        Some(s) => quote!(Some(#s)),
        None => quote!(None),
    }
}

fn write_tokens(tokens: TokenStream, path: &Path) {
    let code = tokens.to_string();
    std::fs::write(path, code)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", path.display()));
}
