//! Rust code generation from parsed registry data.

use super::parse::{ModelEntry as ParsedModel, PlatformFile};
use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use std::path::Path;

/// Generate `quantization.rs` containing `QuantizationType` and `MemoryThreshold`.
pub fn write_quantization(platform: &PlatformFile, out_dir: &Path) {
    let variants: Vec<TokenStream> = platform
        .quantizations
        .keys()
        .map(|serde_name| {
            let variant = to_enum_variant(serde_name);
            quote! {
                #[serde(rename = #serde_name)]
                #variant
            }
        })
        .collect();

    let to_isq_arms: Vec<TokenStream> = platform
        .quantizations
        .iter()
        .map(|(serde_name, isq_variant)| {
            let variant = to_enum_variant(serde_name);
            let isq_ident = format_ident!("{}", isq_variant);
            quote! { Self::#variant => mistralrs::IsqType::#isq_ident }
        })
        .collect();

    let mem_variants: Vec<TokenStream> = MEMORY_THRESHOLDS
        .iter()
        .map(|(name, variant, gb)| {
            let ident = format_ident!("{}", variant);
            let doc = format!("{gb} GB minimum.");
            quote! {
                #[serde(rename = #name)]
                #[doc = #doc]
                #ident
            }
        })
        .collect();

    let mem_bytes_arms: Vec<TokenStream> = MEMORY_THRESHOLDS
        .iter()
        .map(|(_, variant, gb)| {
            let ident = format_ident!("{}", variant);
            let bytes: u64 = gb * 1024 * 1024 * 1024;
            quote! { Self::#ident => #bytes }
        })
        .collect();

    let valid_names: Vec<&String> = platform.quantizations.keys().collect();
    let valid_list = valid_names
        .iter()
        .map(|n| n.as_str())
        .collect::<Vec<_>>()
        .join(", ");

    let tokens = quote! {
        #[doc = "Platform-specific quantization types."]
        #[doc = ""]
        #[doc = "Generated by build.rs from registry TOML files."]
        #[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
        pub enum QuantizationType {
            #(#variants,)*
            #[doc = "Unrecognized quantization string from user config."]
            #[serde(untagged)]
            Other(String),
        }

        impl QuantizationType {
            #[doc = "Return an error if this is an `Other` variant with a helpful message."]
            pub fn validate(&self) -> anyhow::Result<()> {
                if let Self::Other(name) = self {
                    anyhow::bail!(
                        "unknown quantization '{}' — valid options for this platform: {}",
                        name, #valid_list,
                    );
                }
                Ok(())
            }
        }

        #[cfg(feature = "local")]
        impl QuantizationType {
            #[doc = "Convert to the mistralrs `IsqType`."]
            #[doc = ""]
            #[doc = "Panics if called on `Other` — call `validate()` first."]
            pub fn to_isq(&self) -> mistralrs::IsqType {
                match self {
                    #(#to_isq_arms,)*
                    Self::Other(name) => panic!(
                        "cannot convert unknown quantization '{}' to IsqType", name
                    ),
                }
            }
        }

        #[doc = "Minimum system RAM required for a model."]
        #[doc = ""]
        #[doc = "Generated by build.rs from registry TOML files."]
        #[derive(Debug, Clone, Copy, serde::Serialize, serde::Deserialize)]
        pub enum MemoryThreshold {
            #(#mem_variants),*
        }

        impl MemoryThreshold {
            #[doc = "Return the threshold in bytes."]
            pub fn bytes(self) -> u64 {
                match self {
                    #(#mem_bytes_arms),*
                }
            }
        }
    };

    write_tokens(tokens, &out_dir.join("quantization.rs"));
}

/// Generate `registry.rs` containing `ModelEntry`, `MODELS`, `PlatformDefaults`, `DEFAULTS`.
pub fn write_registry(platform: &PlatformFile, out_dir: &Path) {
    let entries: Vec<TokenStream> = platform
        .models
        .iter()
        .map(|(key, entry)| model_entry_tokens(key, entry))
        .collect();

    let text_default = &platform.defaults.text;
    let vision_default = option_str_tokens(platform.defaults.vision.as_deref());
    let quant_default = option_str_tokens(platform.defaults.quantization.as_deref());

    let tokens = quote! {
        #[doc = "A curated model entry from the registry."]
        #[doc = ""]
        #[doc = "Generated by build.rs from registry TOML files."]
        #[derive(Debug, Clone, Copy)]
        pub struct ModelEntry {
            #[doc = "Registry key (e.g. \"qwen3-4b\")."]
            pub key: &'static str,
            #[doc = "Human-readable name."]
            pub name: &'static str,
            #[doc = "HuggingFace model ID."]
            pub model_id: &'static str,
            #[doc = "Loader to use."]
            pub loader: crate::config::Loader,
            #[doc = "Minimum system RAM."]
            pub memory: crate::config::MemoryThreshold,
        }

        #[doc = "All curated models for the current platform."]
        pub const MODELS: &[ModelEntry] = &[
            #(#entries),*
        ];

        #[doc = "Platform defaults from the registry."]
        #[derive(Debug, Clone, Copy)]
        pub struct PlatformDefaults {
            #[doc = "Default text model registry key."]
            pub text: &'static str,
            #[doc = "Default vision model registry key."]
            pub vision: Option<&'static str>,
            #[doc = "Default quantization serde key for ISQ."]
            pub default_quantization: Option<&'static str>,
        }

        #[doc = "Platform defaults for the current build."]
        pub const DEFAULTS: PlatformDefaults = PlatformDefaults {
            text: #text_default,
            vision: #vision_default,
            default_quantization: #quant_default,
        };
    };

    write_tokens(tokens, &out_dir.join("registry.rs"));
}

// ── Helpers ────────────────────────────────────────────────────────

const MEMORY_THRESHOLDS: &[(&str, &str, u64)] = &[
    ("4gb", "Gb4", 4),
    ("8gb", "Gb8", 8),
    ("16gb", "Gb16", 16),
    ("32gb", "Gb32", 32),
    ("64gb", "Gb64", 64),
];

fn to_enum_variant(serde_name: &str) -> proc_macro2::Ident {
    format_ident!("{}", serde_name.to_uppercase())
}

fn loader_tokens(loader: &str) -> TokenStream {
    match loader {
        "text" => quote!(crate::config::Loader::Text),
        "gguf" => quote!(crate::config::Loader::Gguf),
        "vision" => quote!(crate::config::Loader::Vision),
        other => panic!("unknown loader in registry: {other}"),
    }
}

fn memory_tokens(memory: &str) -> TokenStream {
    let ident = format_ident!(
        "{}",
        MEMORY_THRESHOLDS
            .iter()
            .find(|(name, _, _)| *name == memory)
            .unwrap_or_else(|| panic!("unknown memory threshold: {memory}"))
            .1
    );
    quote!(crate::config::MemoryThreshold::#ident)
}

fn option_str_tokens(s: Option<&str>) -> TokenStream {
    match s {
        Some(v) => quote!(Some(#v)),
        None => quote!(None),
    }
}

fn model_entry_tokens(key: &str, entry: &ParsedModel) -> TokenStream {
    let name = &entry.name;
    let model_id = &entry.model_id;
    let loader = loader_tokens(&entry.loader);
    let mem = memory_tokens(&entry.memory);

    quote! {
        ModelEntry {
            key: #key,
            name: #name,
            model_id: #model_id,
            loader: #loader,
            memory: #mem,
        }
    }
}

fn write_tokens(tokens: TokenStream, path: &Path) {
    let code = tokens.to_string();
    std::fs::write(path, code)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", path.display()));
}
