//! Rust code generation from parsed registry data.

use super::parse::RegistryFile;
use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use std::path::Path;

/// Generate `quantization.rs` containing `MemoryThreshold`.
pub fn write_memory_threshold(out_dir: &Path) {
    let mem_variants: Vec<TokenStream> = MEMORY_THRESHOLDS
        .iter()
        .map(|(name, variant, gb)| {
            let ident = format_ident!("{}", variant);
            let doc = format!("{gb} GB minimum.");
            quote! {
                #[serde(rename = #name)]
                #[doc = #doc]
                #ident
            }
        })
        .collect();

    let mem_bytes_arms: Vec<TokenStream> = MEMORY_THRESHOLDS
        .iter()
        .map(|(_, variant, gb)| {
            let ident = format_ident!("{}", variant);
            let bytes: u64 = gb * 1024 * 1024 * 1024;
            quote! { Self::#ident => #bytes }
        })
        .collect();

    let tokens = quote! {
        #[doc = "Minimum system RAM required for a model."]
        #[doc = ""]
        #[doc = "Generated by build.rs from registry TOML files."]
        #[derive(Debug, Clone, Copy, serde::Serialize, serde::Deserialize)]
        pub enum MemoryThreshold {
            #(#mem_variants),*
        }

        impl MemoryThreshold {
            #[doc = "Return the threshold in bytes."]
            pub fn bytes(self) -> u64 {
                match self {
                    #(#mem_bytes_arms),*
                }
            }
        }
    };

    write_tokens(tokens, &out_dir.join("quantization.rs"));
}

/// Generate `registry.rs` containing `ModelEntry`, `MODELS`, `PlatformDefaults`, `DEFAULTS`.
pub fn write_registry(registry: &RegistryFile, out_dir: &Path) {
    let mut entries = Vec::new();
    for (family, entry) in &registry.models {
        for release in &entry.tags {
            entries.push(model_entry_tokens(family, &entry.loader, release));
        }
    }

    let default_key = derive_default_key(&registry.defaults.text);

    let tokens = quote! {
        #[doc = "A curated model entry from the registry."]
        #[doc = ""]
        #[doc = "Generated by build.rs from registry TOML files."]
        #[derive(Debug, Clone, Copy)]
        pub struct ModelEntry {
            #[doc = "Registry key (e.g. \"qwen3-06b\")."]
            pub key: &'static str,
            #[doc = "Human-readable name."]
            pub name: &'static str,
            #[doc = "HuggingFace model ID."]
            pub model_id: &'static str,
            #[doc = "Loader to use."]
            pub loader: crate::config::Loader,
            #[doc = "Minimum system RAM."]
            pub memory: crate::config::MemoryThreshold,
            #[doc = "GGUF filename stem for constructing quantized filenames (e.g. `Qwen3-0.6B`)."]
            pub gguf_stem: Option<&'static str>,
        }

        #[doc = "All curated models for the current platform."]
        pub const MODELS: &[ModelEntry] = &[
            #(#entries),*
        ];

        #[doc = "Platform defaults from the registry."]
        #[derive(Debug, Clone, Copy)]
        pub struct PlatformDefaults {
            #[doc = "Default model registry key."]
            pub text: &'static str,
        }

        #[doc = "Platform defaults for the current build."]
        pub const DEFAULTS: PlatformDefaults = PlatformDefaults {
            text: #default_key,
        };
    };

    write_tokens(tokens, &out_dir.join("registry.rs"));
}

// ── Helpers ────────────────────────────────────────────────────────

const MEMORY_THRESHOLDS: &[(&str, &str, u64)] = &[
    ("4gb", "Gb4", 4),
    ("8gb", "Gb8", 8),
    ("16gb", "Gb16", 16),
    ("32gb", "Gb32", 32),
    ("64gb", "Gb64", 64),
];

fn loader_tokens(loader: &str) -> TokenStream {
    match loader {
        "text" => quote!(crate::config::Loader::Text),
        "gguf" => quote!(crate::config::Loader::Gguf),
        "vision" => quote!(crate::config::Loader::Vision),
        other => panic!("unknown loader in registry: {other}"),
    }
}

fn memory_tokens(memory: &str) -> TokenStream {
    let ident = format_ident!(
        "{}",
        MEMORY_THRESHOLDS
            .iter()
            .find(|(name, _, _)| *name == memory)
            .unwrap_or_else(|| panic!("unknown memory threshold: {memory}"))
            .1
    );
    quote!(crate::config::MemoryThreshold::#ident)
}

/// Parse a release string like "0.6b", "14b" into a float (billions).
fn parse_param_size(release: &str) -> f64 {
    let s = release.trim_end_matches('b').trim_end_matches('B');
    s.parse::<f64>()
        .unwrap_or_else(|_| panic!("cannot parse release size: {release}"))
}

/// Map param count to memory threshold string.
fn derive_memory(release: &str) -> &'static str {
    let size = parse_param_size(release);
    if size <= 2.0 {
        "4gb"
    } else if size <= 4.0 {
        "8gb"
    } else if size <= 8.0 {
        "16gb"
    } else if size <= 16.0 {
        "32gb"
    } else {
        "64gb"
    }
}

/// Title-case a family name segment.
/// Segments ≤2 chars are uppercased (e.g. "vl" → "VL").
/// Longer segments get first char uppercased (e.g. "qwen3" → "Qwen3").
fn title_case_segment(s: &str) -> String {
    if s.len() <= 2 {
        s.to_uppercase()
    } else {
        let mut chars = s.chars();
        match chars.next() {
            Some(c) => c.to_uppercase().to_string() + chars.as_str(),
            None => String::new(),
        }
    }
}

/// Title-case a full family name: split on `-`, title-case each segment, rejoin.
/// e.g. "qwen3-vl" → "Qwen3-VL", "llama-3-1" → "Llama-3-1"
fn title_case_family(family: &str) -> String {
    family
        .split('-')
        .map(|seg| {
            if seg.chars().all(|c| c.is_ascii_digit()) {
                seg.to_string()
            } else {
                title_case_segment(seg)
            }
        })
        .collect::<Vec<_>>()
        .join("-")
}

/// Uppercase the trailing 'b' in a release string.
/// e.g. "0.6b" → "0.6B", "14b" → "14B"
fn upper_release(release: &str) -> String {
    if let Some(prefix) = release.strip_suffix('b') {
        format!("{prefix}B")
    } else {
        release.to_string()
    }
}

/// Derive the registry key: `{family}-{release_slug}` where dots are removed.
/// e.g. ("qwen3", "0.6b") → "qwen3-06b"
fn derive_key(family: &str, release: &str) -> String {
    let slug = release.replace('.', "");
    format!("{family}-{slug}")
}

/// Derive HF model ID: `openwalrus/{family}-{Release}`.
/// e.g. ("qwen3", "0.6b") → "openwalrus/qwen3-0.6B"
fn derive_model_id(family: &str, release: &str) -> String {
    format!("openwalrus/{family}-{}", upper_release(release))
}

/// Derive GGUF file stem: title-cased family + release.
/// e.g. ("qwen3", "0.6b") → "Qwen3-0.6B"
fn derive_stem(family: &str, release: &str) -> String {
    format!("{}-{}", title_case_family(family), upper_release(release))
}

/// Derive human-readable name: title-cased family + release.
/// e.g. ("qwen3", "0.6b") → "Qwen3 0.6B"
fn derive_name(family: &str, release: &str) -> String {
    format!("{} {}", title_case_family(family), upper_release(release))
}

/// Convert default specifier "family:release" → registry key.
/// e.g. "qwen3-vl:4b" → "qwen3-vl-4b"
fn derive_default_key(specifier: &str) -> String {
    let (family, release) = specifier.split_once(':').unwrap_or_else(|| {
        panic!("invalid default specifier (expected family:release): {specifier}")
    });
    derive_key(family, release)
}

fn model_entry_tokens(family: &str, loader: &str, release: &str) -> TokenStream {
    let key = derive_key(family, release);
    let name = derive_name(family, release);
    let model_id = derive_model_id(family, release);
    let loader_tok = loader_tokens(loader);
    let mem = memory_tokens(derive_memory(release));
    let gguf_stem = if loader == "gguf" {
        let stem = derive_stem(family, release);
        quote!(Some(#stem))
    } else {
        quote!(None)
    };

    quote! {
        ModelEntry {
            key: #key,
            name: #name,
            model_id: #model_id,
            loader: #loader_tok,
            memory: #mem,
            gguf_stem: #gguf_stem,
        }
    }
}

fn write_tokens(tokens: TokenStream, path: &Path) {
    let code = tokens.to_string();
    std::fs::write(path, code)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", path.display()));
}
