//! Provider configuration.
//!
//! `ProviderConfig` for remote providers — kind inferred from model name
//! prefix via `kind()`. Local models use the built-in registry instead.
//! `Loader` selects which mistralrs builder to use for local models.

use anyhow::{Result, bail};
use compact_str::CompactString;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

/// API protocol standard for remote providers.
///
/// Only two wire formats exist: OpenAI-compatible and Anthropic.
/// Defaults to `OpenAI` when omitted in config.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ApiStandard {
    /// OpenAI-compatible chat completions API (covers DeepSeek, Grok, Qwen, Kimi, Ollama, etc.).
    #[default]
    OpenAI,
    /// Anthropic Messages API.
    Anthropic,
}

/// Remote provider configuration.
///
/// Any model name is valid — the `standard` field (or auto-detection from
/// `base_url`) determines which API protocol to use. Local models are handled
/// by the built-in registry, not by this config.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ProviderConfig {
    /// Model identifier sent to the remote API.
    pub model: CompactString,
    /// API key for remote providers. Supports `${ENV_VAR}` expansion at the
    /// daemon layer.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub api_key: Option<String>,
    /// Base URL for the remote provider endpoint.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub base_url: Option<String>,
    /// API protocol standard. Defaults to OpenAI if omitted.
    #[serde(default)]
    pub standard: ApiStandard,
}

impl ProviderConfig {
    /// Resolve the effective API standard.
    ///
    /// Returns `Anthropic` if the field is explicitly set to `Anthropic`,
    /// or if `base_url` contains "anthropic". Otherwise `OpenAI`.
    pub fn effective_standard(&self) -> ApiStandard {
        if self.standard == ApiStandard::Anthropic {
            return ApiStandard::Anthropic;
        }
        if let Some(url) = &self.base_url
            && url.contains("anthropic")
        {
            return ApiStandard::Anthropic;
        }
        ApiStandard::OpenAI
    }

    /// Validate field combinations.
    ///
    /// Called on startup and on provider add/reload.
    pub fn validate(&self) -> Result<()> {
        if self.model.is_empty() {
            bail!("model is required");
        }
        // Remote providers: api_key is required unless base_url is set
        // (e.g. Ollama which is keyless with a local base_url).
        if self.api_key.is_none() && self.base_url.is_none() {
            bail!(
                "remote provider '{}' requires api_key or base_url",
                self.model
            );
        }
        Ok(())
    }
}

/// Selects which mistralrs model builder to use for local inference.
///
/// Defaults to `Text` when omitted in config.
#[derive(Debug, Serialize, Deserialize, Clone, Copy, Default)]
#[serde(rename_all = "snake_case")]
pub enum Loader {
    /// `TextModelBuilder` — standard text models.
    #[default]
    Text,
    /// `GgufModelBuilder` — GGUF quantized models.
    Gguf,
    /// `VisionModelBuilder` — vision-language models.
    Vision,
}

/// Custom HuggingFace model configuration for local inference.
///
/// Allows users to run any HuggingFace model not in the built-in registry.
/// Memory and quantization are auto-selected at runtime based on system RAM.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HfModelConfig {
    /// HuggingFace repository ID (e.g. `"myorg/MyModel-7B-GGUF"`).
    pub model_id: String,
    /// Which mistralrs builder to use.
    #[serde(default)]
    pub loader: Loader,
    /// Explicit GGUF filename (required for GGUF models without a standard
    /// naming convention).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub gguf_file: Option<String>,
    /// Custom chat template override.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub chat_template: Option<String>,
}

/// Model provider configuration for the daemon.
///
/// Remote providers are configured in `providers`. Local models come from the
/// built-in registry or from user-defined `models`. The active model name
/// lives in `[walrus].model`.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct ModelConfig {
    /// Optional embedding model
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub embedding: Option<CompactString>,
    /// Remote providers (local models come from the built-in registry)
    #[serde(default)]
    pub providers: BTreeMap<CompactString, ProviderConfig>,
    /// Custom HuggingFace models for local inference
    #[serde(default)]
    pub models: BTreeMap<CompactString, HfModelConfig>,
}

// MemoryThreshold is generated by build.rs from registry TOML files.
include!(concat!(env!("OUT_DIR"), "/quantization.rs"));
