//! Provider configuration.
//!
//! `ProviderConfig` for remote providers — kind inferred from model name
//! prefix via `kind()`. Local models use the built-in registry instead.
//! `Loader` selects which mistralrs builder to use for local models.

use anyhow::{Result, bail};
use compact_str::CompactString;
use serde::{Deserialize, Serialize};

/// Remote provider configuration.
///
/// Provider kind is inferred from the model name prefix — no explicit tag.
/// Local models are handled by the built-in registry, not by this config.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ProviderConfig {
    /// Model identifier. Uses known prefixes (`deepseek-*`, `gpt-*`,
    /// `claude-*`, etc.) to detect the provider kind.
    pub model: CompactString,
    /// API key for remote providers. Supports `${ENV_VAR}` expansion at the
    /// daemon layer.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub api_key: Option<String>,
    /// Base URL override for remote providers.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub base_url: Option<String>,
}

impl ProviderConfig {
    /// Detect the provider kind from the model name.
    pub fn kind(&self) -> Result<ProviderKind> {
        ProviderKind::from_model(&self.model)
    }

    /// Validate field combinations.
    ///
    /// Called on startup and on provider add/reload.
    pub fn validate(&self) -> Result<()> {
        if self.model.is_empty() {
            bail!("model is required");
        }
        self.kind()?;
        // Remote providers: api_key is required unless base_url is set
        // (e.g. Ollama which is keyless with a local base_url).
        if self.api_key.is_none() && self.base_url.is_none() {
            bail!(
                "remote provider '{}' requires api_key or base_url",
                self.model
            );
        }
        Ok(())
    }
}

/// Remote provider kind, inferred from the model name at runtime.
///
/// Not serialized — purely a dispatch enum for remote providers.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProviderKind {
    DeepSeek,
    OpenAI,
    Claude,
    Grok,
    Qwen,
    Kimi,
}

impl ProviderKind {
    /// Detect provider kind from a model name string.
    ///
    /// Matches known remote prefixes. Returns an error for unknown prefixes
    /// or HuggingFace repo IDs (local models use the built-in registry).
    pub fn from_model(model: &str) -> Result<Self> {
        if model.contains('/') {
            bail!(
                "'{model}' looks like a HuggingFace repo ID — use the model registry for local models"
            );
        }

        let prefixes: &[(&[&str], ProviderKind)] = &[
            (&["deepseek-"], ProviderKind::DeepSeek),
            (&["gpt-", "o1-", "o3-", "o4-"], ProviderKind::OpenAI),
            (&["claude-"], ProviderKind::Claude),
            (&["grok-"], ProviderKind::Grok),
            (&["qwen-", "qwq-"], ProviderKind::Qwen),
            (&["kimi-", "moonshot-"], ProviderKind::Kimi),
        ];

        for (patterns, kind) in prefixes {
            for prefix in *patterns {
                if model.starts_with(prefix) {
                    return Ok(*kind);
                }
            }
        }

        bail!("unknown model prefix: '{model}' — cannot detect provider kind")
    }

    /// Human-readable name for logging.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::DeepSeek => "deepseek",
            Self::OpenAI => "openai",
            Self::Claude => "claude",
            Self::Grok => "grok",
            Self::Qwen => "qwen",
            Self::Kimi => "kimi",
        }
    }
}

/// Selects which mistralrs model builder to use for local inference.
///
/// Defaults to `Text` when omitted in config.
#[derive(Debug, Serialize, Deserialize, Clone, Copy, Default)]
#[serde(rename_all = "snake_case")]
pub enum Loader {
    /// `TextModelBuilder` — standard text models.
    #[default]
    Text,
    /// `GgufModelBuilder` — GGUF quantized models.
    Gguf,
    /// `VisionModelBuilder` — vision-language models.
    Vision,
}

// MemoryThreshold is generated by build.rs from registry TOML files.
include!(concat!(env!("OUT_DIR"), "/quantization.rs"));
